CREATE TABLE FermentationLog
(
	[Id] INTEGER PRIMARY KEY,
	[Name] TEXT NOT NULL,
	[Temperature] DECIMAL NOT NULL,
	[Gravity] DECIMAL NOT NULL,
	[Angle] DECIMAL NOT NULL,
	[DeviceId] INTEGER NOT NULL,
	[Battery] DECIMAL NOT NULL,
	[RSSI] INTEGER NOT NULL,
	[Created] DateTime default CURRENT_TIMESTAMP	
)
